"""Domain core: users, clinics, clinicians, services, appointments, audit log.

Revision ID: 0001
Revises:
Create Date: 2026-09-26

Hand-written (not autogenerated) so the two things autogenerate cannot express are explicit and
readable: the ``btree_gist`` extension and the appointment double-booking EXCLUDE constraint.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Enum types are created explicitly (create_type=False on the columns) so this reads top-to-bottom
# and works the same in online and offline (--sql) mode.
_USER_ROLE = postgresql.ENUM(
    "PATIENT",
    "CLINICIAN",
    "CLINIC_ADMIN",
    "PLATFORM_ADMIN",
    name="user_role",
    create_type=False,
)
_APPOINTMENT_STATUS = postgresql.ENUM(
    "REQUESTED",
    "CONFIRMED",
    "COMPLETED",
    "CANCELLED",
    "NO_SHOW",
    name="appointment_status",
    create_type=False,
)

_TIMESTAMPS = (
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    ),
    sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        nullable=False,
    ),
)


def upgrade() -> None:
    # btree_gist lets a plain-equality column (clinician_id) and a range share one GiST index,
    # which is what the EXCLUDE constraint below needs.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute(
        "CREATE TYPE user_role AS ENUM "
        "('PATIENT', 'CLINICIAN', 'CLINIC_ADMIN', 'PLATFORM_ADMIN')"
    )
    op.execute(
        "CREATE TYPE appointment_status AS ENUM "
        "('REQUESTED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')"
    )

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("full_name", sa.String(200), nullable=False),
        sa.Column("role", _USER_ROLE, nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        *_TIMESTAMPS,
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "clinics",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("timezone", sa.String(64), nullable=False),
        sa.Column("address", sa.String(500), nullable=False),
        sa.Column(
            "cancellation_cutoff_hours",
            sa.Integer(),
            server_default=sa.text("24"),
            nullable=False,
        ),
        *_TIMESTAMPS,
    )

    op.create_table(
        "clinicians",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "clinic_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clinics.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("specialty", sa.String(100), nullable=False),
        sa.Column("buffer_minutes", sa.Integer(), server_default=sa.text("0"), nullable=False),
        *_TIMESTAMPS,
    )
    op.create_index("ix_clinicians_clinic_id", "clinicians", ["clinic_id"])
    op.create_index("ix_clinicians_user_id", "clinicians", ["user_id"], unique=True)

    op.create_table(
        "clinician_working_hours",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "clinician_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clinicians.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.CheckConstraint("weekday >= 0 AND weekday <= 6", name="ck_working_hours_weekday_range"),
        sa.CheckConstraint("end_time > start_time", name="ck_working_hours_time_order"),
    )
    op.create_index(
        "ix_clinician_working_hours_clinician_id", "clinician_working_hours", ["clinician_id"]
    )

    op.create_table(
        "services",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "clinic_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clinics.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(3), server_default="USD", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.CheckConstraint("duration_minutes > 0", name="ck_service_duration_positive"),
        sa.CheckConstraint("price_cents >= 0", name="ck_service_price_non_negative"),
        *_TIMESTAMPS,
    )
    op.create_index("ix_services_clinic_id", "services", ["clinic_id"])

    op.create_table(
        "appointments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "clinic_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clinics.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "clinician_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clinicians.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "patient_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "service_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("services.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            _APPOINTMENT_STATUS,
            server_default=sa.text("'REQUESTED'"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("cancellation_reason", sa.String(500), nullable=True),
        *_TIMESTAMPS,
    )
    op.create_index("ix_appointments_clinic_id", "appointments", ["clinic_id"])
    op.create_index("ix_appointments_clinician_id", "appointments", ["clinician_id"])
    op.create_index("ix_appointments_patient_id", "appointments", ["patient_id"])
    op.create_index("ix_appointments_service_id", "appointments", ["service_id"])
    # The double-booking guard: no two live appointments for one clinician may overlap in time.
    op.execute(
        """
        ALTER TABLE appointments
        ADD CONSTRAINT ck_appointment_no_double_booking
        EXCLUDE USING gist (
            clinician_id WITH =,
            tstzrange(starts_at, ends_at, '[)') WITH &&
        ) WHERE (status NOT IN ('CANCELLED', 'NO_SHOW'))
        """
    )

    op.create_table(
        "audit_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "actor_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("action", sa.String(100), nullable=False),
        sa.Column("entity_type", sa.String(100), nullable=False),
        sa.Column("entity_id", sa.String(64), nullable=False),
        sa.Column("before", postgresql.JSONB(), nullable=True),
        sa.Column("after", postgresql.JSONB(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index("ix_audit_log_actor_id", "audit_log", ["actor_id"])
    op.create_index("ix_audit_log_entity_id", "audit_log", ["entity_id"])


def downgrade() -> None:
    op.drop_table("audit_log")
    # Dropping the table also drops its EXCLUDE constraint and indexes.
    op.drop_table("appointments")
    op.drop_table("services")
    op.drop_table("clinician_working_hours")
    op.drop_table("clinicians")
    op.drop_table("clinics")
    op.drop_table("users")
    op.execute("DROP TYPE IF EXISTS appointment_status")
    op.execute("DROP TYPE IF EXISTS user_role")
